services:
  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: dev12345
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - 5432:5432
      
volumes:
  pgdata:
